In [52]:
import numpy as np
import tensorflow as tf

In [53]:
x=np.random.normal(size=[10,5])
cls=3
X=tf.placeholder(tf.int32,[10,5])
X_oneHot=tf.one_hot(X,cls)
split=tf.split(X_oneHot,5,1)
squeezed=tf.squeeze(split[0],squeeze_dims=1)

In [54]:
x

array([[-1.8678947 , -1.03947454, -0.50299818,  1.27730074, -1.22779056],
       [-1.00102135,  1.34505781,  0.23698819, -1.29406424, -1.08705144],
       [-0.06898929, -0.417531  , -0.77868447, -1.60435273, -0.6834383 ],
       [-1.35751005,  1.69819093,  0.91441346,  0.18692313, -0.22270985],
       [ 0.69809774, -1.2689746 , -0.20529614, -0.38509324,  0.73555404],
       [ 0.19010046, -0.02144384,  0.11980878,  1.42496587, -1.38705119],
       [ 1.14440769,  0.25691272, -0.04289939, -1.66702085,  0.97450625],
       [-0.53850063,  0.33373772, -1.25007045,  0.04744099,  1.8124761 ],
       [ 1.20906698, -1.2598689 ,  0.21495288,  1.0481649 ,  0.1683007 ],
       [ 0.76616069,  1.09291631, -0.7959546 ,  0.67133807,  0.91011454]])

In [55]:
with tf.Session() as sess:
    X_oneHot=sess.run(X_oneHot,feed_dict={X:x})
    split=sess.run(split,feed_dict={X:x})
    squeezed=sess.run(squeezed,feed_dict={X:x})
    print(squeezed)
    

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [56]:
print(split)

[array([[[0., 0., 0.]],

       [[0., 0., 0.]],

       [[1., 0., 0.]],

       [[0., 0., 0.]],

       [[1., 0., 0.]],

       [[1., 0., 0.]],

       [[0., 1., 0.]],

       [[1., 0., 0.]],

       [[0., 1., 0.]],

       [[1., 0., 0.]]], dtype=float32), array([[[0., 0., 0.]],

       [[0., 1., 0.]],

       [[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 0.]],

       [[1., 0., 0.]],

       [[1., 0., 0.]],

       [[1., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 1., 0.]]], dtype=float32), array([[[1., 0., 0.]],

       [[1., 0., 0.]],

       [[1., 0., 0.]],

       [[1., 0., 0.]],

       [[1., 0., 0.]],

       [[1., 0., 0.]],

       [[1., 0., 0.]],

       [[0., 0., 0.]],

       [[1., 0., 0.]],

       [[1., 0., 0.]]], dtype=float32), array([[[0., 1., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]],

       [[1., 0., 0.]],

       [[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 0.]],

       [[1., 0., 0.]],

       [[0., 1., 0.]],

       [[1., 0.

In [30]:
print(X_oneHot)

[[[1. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]
  [0. 1. 0.]
  [1. 0. 0.]]

 [[0. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]
  [0. 0. 0.]
  [0. 1. 0.]]

 [[1. 0. 0.]
  [1. 0. 0.]
  [0. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]]

 [[1. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]]

 [[1. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]]

 [[1. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]
  [0. 0. 0.]]

 [[1. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]
  [0. 0. 0.]]

 [[0. 1. 0.]
  [1. 0. 0.]
  [0. 1. 0.]
  [1. 0. 0.]
  [0. 0. 0.]]

 [[1. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]]]
